flat_database.Rmd:
  path: dev/flat_database.Rmd
  state: active
  R: R/fct_comics_db.R
  tests: tests/testthat/test-fct_comics_db.R
  vignettes: []
  inflate:
    flat_file: dev/flat_database.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_mod110.Rmd:
  path: dev/flat_mod110.Rmd
  state: active
  R: R/fct_mod_110.R
  tests: tests/testthat/test-fct_mod_110.R
  vignettes: []
  inflate:
    flat_file: dev/flat_mod110.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_mod200.Rmd:
  path: dev/flat_mod200.Rmd
  state: active
  R: R/fct_mod_200.R
  tests: tests/testthat/test-fct_mod_200.R
  vignettes: []
  inflate:
    flat_file: dev/flat_mod200.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_open_library.Rmd:
  path: dev/flat_open_library.Rmd
  state: active
  R:
  - R/fct_open_library.R
  - R/get_cover.R
  tests:
  - tests/testthat/test-fct_open_library.R
  - tests/testthat/test-get_cover.R
  vignettes: []
  inflate:
    flat_file: dev/flat_open_library.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
