flat_database.Rmd:
  path: dev/flat_database.Rmd
  state: active
  R: R/fct_comics_db.R
  tests: tests/testthat/test-fct_comics_db.R
  vignettes: []
  inflate:
    flat_file: dev/flat_database.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_mod110.Rmd:
  path: dev/flat_mod110.Rmd
  state: active
  R: R/fct_mod_110.R
  tests: tests/testthat/test-fct_mod_110.R
  vignettes: []
  inflate:
    flat_file: dev/flat_mod110.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_mod130.Rmd:
  path: dev/flat_mod130.Rmd
  state: active
  R:
  - R/create_html_for_modal_modify_book_in_collection.R
  - R/fct_mod_300.R
  - R/prepare_comics_db_to_see_wishlist.R
  tests:
  - tests/testthat/test-prepare_comics_db_to_see_wishlist.R
  - tests/testthat/test-fct_mod_300.R
  - tests/testthat/test-create_html_for_modal_modify_book_in_collection.R
  vignettes: []
  inflate:
    flat_file: dev/flat_mod130.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_mod300_400.Rmd:
  path: dev/flat_mod300_400.Rmd
  state: active
  R:
  - R/fct_mod300_400.R
  - R/call_sweet_alert_depending_on_db_append.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_mod300_400.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_open_library.Rmd:
  path: dev/flat_open_library.Rmd
  state: active
  R: R/fct_open_library.R
  tests: tests/testthat/test-fct_open_library.R
  vignettes: []
  inflate:
    flat_file: dev/flat_open_library.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_spinner.Rmd:
  path: dev/flat_spinner.Rmd
  state: active
  R: R/fct_spinner.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_spinner.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_webcam.Rmd:
  path: dev/flat_webcam.Rmd
  state: active
  R: R/fct_webcam.R
  tests: tests/testthat/test-fct_webcam.R
  vignettes: []
  inflate:
    flat_file: dev/flat_webcam.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
