flat_database.Rmd:
  path: dev/flat_database.Rmd
  state: active
  R: R/fct_comics_db.R
  tests: tests/testthat/test-fct_comics_db.R
  vignettes: []
  inflate:
    flat_file: dev/flat_database.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_mod110.Rmd:
  path: dev/flat_mod110.Rmd
  state: active
  R: R/create_html_for_modal_api_search_result.R
  tests: tests/testthat/test-create_html_for_modal_api_search_result.R
  vignettes: []
  inflate:
    flat_file: dev/flat_mod110.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_mod130.Rmd:
  path: dev/flat_mod130.Rmd
  state: active
  R:
  - R/extract_nstars_from_selectinput.R
  - R/make_stars_rating_div.R
  - R/fct_mod_130.R
  tests:
  - tests/testthat/test-make_stars_rating_div.R
  - tests/testthat/test-extract_nstars_from_selectinput.R
  vignettes: []
  inflate:
    flat_file: dev/flat_mod130.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_open_library.Rmd:
  path: dev/flat_open_library.Rmd
  state: active
  R:
  - R/fct_open_library.R
  - R/get_cover.R
  tests:
  - tests/testthat/test-fct_open_library.R
  - tests/testthat/test-get_cover.R
  vignettes: []
  inflate:
    flat_file: dev/flat_open_library.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
flat_webcam.Rmd:
  path: dev/flat_webcam.Rmd
  state: active
  R:
  - R/fct_webcam.R
  - R/export_img_from_dataurl.R
  tests:
  - tests/testthat/test-fct_webcam.R
  - tests/testthat/test-export_img_from_dataurl.R
  vignettes: []
  inflate:
    flat_file: dev/flat_webcam.Rmd
    vignette_name: .na
    open_vignette: true
    check: false
    document: true
    overwrite: ask
